package(default_visibility = ["//visibility:public"])

scala_library(
    name = "foo",
    srcs = glob(["*.scala"]),
    deps = [
        "@com_google_zetasql//java/com/google/zetasql:types",
        "@com_google_zetasql//java/com/google/zetasql:client"
    ]
)

